version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: product_naming_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d product_naming_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/product_naming_db
    volumes:
      - .:/app

volumes:
  postgres_data: 