version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: product_naming_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 